name: Changesets
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm exec changeset version
          commit: "chore: update versions"
          title: "chore: update versions"
          createGithubReleases: true,
          publish: pnpm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
