name: Changesets
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: create and publish versions
      uses: changesets/action@v1
      with:
        version: pnpm exec changeset version
        commit: "chore: update versions"
        title: "chore: update versions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
